environment:
  TWINE_USERNAME:
    secure: sUo+lYht329nQC5JCxEB8w==
  TWINE_PASSWORD:
    secure: mjSxOmR8POpeVSL9mwOnH2XQAn9Trj5wn6dbmCIwgTSr2qjfm/y1UoQ2XkYV9QpATp1xLUKalIDc62bORmIMKe6GkhDayUymLC6RM8KRZqM93aPoNXst9c5YfdUVbJuubk1QsJ/wE8KZrr6jrcXM3H7rfiq9Z8NtEud1XDD/d8MKbR9LkL4Y9ACI12jfayQ+uwaTOMhs9/1XlT92FEPGqy0Qlr/zXLd7TixOkAB/cyqYJdD3B6+fyvqxFxPVrA+iWhldv60ERQmlXW/j7WbPCw==
  CODACY_PROJECT_TOKEN:
    secure: xprpiCGL823NKrs/K2Cps1UVBEmpezXReLxcfLyU1M43ZBBOK91xvjdIJamYKi8D
  DEPLOY_ONLY: false
  matrix:
  - PYTHON: C:\Python35-x64\python.exe
    platform: x64
  - PYTHON: C:\Python35\python.exe
    platform: Any CPU
  - PYTHON: C:\Python36-x64\python.exe
    platform: x64
  - PYTHON: C:\Python36\python.exe
    platform: Any CPU
  - PYTHON: C:\Python37-x64\python.exe
    platform: x64
  - PYTHON: C:\Python37\python.exe
    platform: Any CPU
  - PYTHON: C:\Python38-x64\python.exe
    platform: x64
  - PYTHON: C:\Python38\python.exe
    platform: Any CPU
  - PYPY3: pypy3.6-v7.2.0
    platform: Any CPU

matrix:
  allow_failures:
    - DEPLOY_ONLY: true
clone_depth: 50

init:
- cmd: "if %APPVEYOR_REPO_TAG%==false if %DEPLOY_ONLY%==true exit /b 1"

install:
- cmd: "git submodule update --init --recursive"
- ps: ". .appveyor/install_python.ps1"
- cmd: "%ACTIVATE_VENV%"
- cmd: "set PATH=%APPVEYOR_BUILD_FOLDER%\\venv\\bin;%PATH%"
- cmd: "set PATH=%PATH%;C:\\MinGW\\bin"
- cmd: "python --version"
- cmd: "pip --version"
- cmd: "pip install --upgrade setuptools"
- cmd: "pip install --requirement requirements.txt"
- cmd: "python setup.py build sdist develop bdist_wheel"
build: off
before_test:
- cmd: "pip install pytest pytest-cov"
test_script:
- ps: "pytest -v"

on_success:
- pip install codacy-coverage python-coveralls
- coverage xml
- if defined CODACY_PROJECT_TOKEN python-codacy-coverage -r coverage.xml || cd .

deploy_script:
- "if defined APPVEYOR_REPO_TAG_NAME pip install twine"
- "if defined APPVEYOR_REPO_TAG_NAME twine upload --skip-existing dist/*"
